require "pathname"

app_root = File.expand_path("..", __dir__)
toolkit_root = ENV["IOS_RELEASE_TOOLKIT_PATH"] || File.expand_path("../../ios-release-toolkit", __dir__)
shared_fastfile = File.join(toolkit_root, "fastlane/SharedFastfile")

UI.user_error!("iOS release toolkit not found at #{toolkit_root}.") unless File.file?(shared_fastfile)

ENV["IOS_RELEASE_APP_ROOT"] = app_root
ENV["IOS_RELEASE_CONFIG_PATH"] ||= File.join(app_root, "fastlane/AppConfig.yml")

relative_shared_fastfile = Pathname.new(shared_fastfile).relative_path_from(Pathname.new(File.expand_path(__dir__))).to_s
import relative_shared_fastfile
